import '../translation_keys.dart';

final Map<String, String> hiIN = {
  TrKeys.welcome: 'ड्राइवर में आपका स्वागत है',
  TrKeys.loginSubtitle: 'अपने मोबाइल नंबर से लॉगिन करें',
  TrKeys.enterMobile: 'मोबाइल नंबर दर्ज करें',
  TrKeys.continueBtn: 'जारी रखें',
  TrKeys.termsConditions: 'नियम और शर्तें',
  TrKeys.privacyPolicy: 'गोपनीयता नीति',
  TrKeys.verifyNumber: 'नंबर सत्यापित करें',
  TrKeys.enterCodeDes: 'OTP दर्ज करें जो भेजा गया है',
  TrKeys.otpButtonName: 'OTP सत्यापित करें',
  TrKeys.didNotReceiveCode: 'OTP नहीं मिला?',
  TrKeys.resendCode: 'पुनः भेजें',
  TrKeys.sms: 'SMS',
  TrKeys.whatsapp: 'WhatsApp',
  TrKeys.selectLanguage: 'भाषा चुनें',
  TrKeys.languageSubtitle: 'अपनी पसंदीदा भाषा चुनें',
  TrKeys.home: 'होम',
  TrKeys.account: 'अकाउंट',
  TrKeys.payments: 'भुगतान',
  TrKeys.assignedTrips: 'सौंपी गई यात्राएं',
  TrKeys.tripHistory: 'यात्रा इतिहास',
  TrKeys.advanceRequests: 'अग्रिम अनुरोध',
  TrKeys.salaryRequests: 'वेतन अनुरोध',
  TrKeys.logout: 'लॉगआउट',
  TrKeys.tripDetails: 'यात्रा विवरण',
  TrKeys.startTrip: 'यात्रा शुरू करें',
  TrKeys.confirmPickup: 'पिकअप पुष्टि करें',
  TrKeys.completeTrip: 'यात्रा पूर्ण करें',
  TrKeys.acceptTrip: 'स्वीकार',
  TrKeys.rejectTrip: 'अस्वीकार',
  TrKeys.from: 'से',
  TrKeys.to: 'तक',
  TrKeys.vehicle: 'वाहन',
  TrKeys.load: 'माल',
  TrKeys.distance: 'दूरी',
  TrKeys.status: 'स्थिति',
  TrKeys.noTrips: 'कोई यात्रा नहीं',
  TrKeys.tripAssigned: 'यात्रा सौंपी गई',
  TrKeys.acceptOrReject: 'आपको एक नई यात्रा सौंपी गई है।',
  TrKeys.requestAdvance: 'अग्रिम अनुरोध करें',
  TrKeys.amount: 'राशि (₹)',
  TrKeys.reason: 'कारण',
  TrKeys.submit: 'सबमिट',
  TrKeys.advancePending: 'अनुमोदन के लिए प्रतीक्षा',
  TrKeys.advanceApproved: 'स्वीकृत',
  TrKeys.advanceRejected: 'अस्वीकृत',
  TrKeys.salary: 'वेतन',
  TrKeys.requestSalary: 'वेतन अनुरोध करें',
  TrKeys.salaryPending: 'वेतन लंबित',
  TrKeys.salaryApproved: 'वेतन स्वीकृत',
  TrKeys.salaryRejected: 'वेतन अस्वीकृत',
  TrKeys.earnedSalary: 'अर्जित वेतन',
  TrKeys.approvedAmount: 'स्वीकृत राशि',
  TrKeys.loading: 'लोड हो रहा है...',
  TrKeys.retry: 'पुनः प्रयास',
  TrKeys.cancel: 'रद्द करें',
  TrKeys.confirm: 'पुष्टि करें',
  TrKeys.yes: 'हाँ',
  TrKeys.no: 'नहीं',
  TrKeys.ok: 'ठीक है',
  TrKeys.error: 'त्रुटि',
  TrKeys.success: 'सफलता',
  TrKeys.noData: 'कोई डेटा उपलब्ध नहीं',
  TrKeys.km: 'किमी',
  TrKeys.rupee: '₹',
  TrKeys.notAssignedToOwner:
      'आप किसी मालिक को नहीं सौंपे गए हैं। व्यवस्थापक से संपर्क करें।',
  TrKeys.kycIncomplete: 'KYC अपूर्ण है। कृपया अपना लाइसेंस अपलोड करें।',

  // Tracking
  TrKeys.trackingActive: 'ट्रिप ट्रैकिंग चालू है',
  TrKeys.trackingStarted: 'GPS ट्रैकिंग शुरू हो गई',
  TrKeys.trackingStopped: 'GPS ट्रैकिंग रुक गई',
  TrKeys.gpsDisabled: 'GPS बंद है। कृपया लोकेशन चालू करें।',
  TrKeys.enableGps: 'GPS चालू करें',
  TrKeys.locationPermissionRequired: 'ट्रिप ट्रैकिंग के लिए लोकेशन अनुमति आवश्यक है।',
  TrKeys.backgroundLocationRequired: 'आपकी ट्रिप ट्रैक करने के लिए बैकग्राउंड लोकेशन एक्सेस ज़रूरी है।',
};
