import '../translation_keys.dart';

final Map<String, String> teIN = {
  TrKeys.welcome: 'డ్రైవర్ కు స్వాగతం',
  TrKeys.loginSubtitle: 'మీ మొబైల్ నంబర్‌తో లాగిన్ అవండి',
  TrKeys.enterMobile: 'మొబైల్ నంబర్ నమోదు చేయండి',
  TrKeys.continueBtn: 'కొనసాగించు',
  TrKeys.termsConditions: 'నిబంధనలు & షరతులు',
  TrKeys.privacyPolicy: 'గోప్యతా విధానం',
  TrKeys.verifyNumber: 'నంబర్ నిర్ధారించండి',
  TrKeys.enterCodeDes: 'OTP నమోదు చేయండి',
  TrKeys.otpButtonName: 'OTP ధృవీకరించండి',
  TrKeys.didNotReceiveCode: 'OTP అందలేదా?',
  TrKeys.resendCode: 'మళ్ళీ పంపండి',
  TrKeys.sms: 'SMS',
  TrKeys.whatsapp: 'WhatsApp',
  TrKeys.selectLanguage: 'భాష ఎంచుకోండి',
  TrKeys.languageSubtitle: 'మీకు ఇష్టమైన భాష ఎంచుకోండి',
  TrKeys.home: 'హోమ్',
  TrKeys.account: 'ఖాతా',
  TrKeys.payments: 'చెల్లింపులు',
  TrKeys.assignedTrips: 'కేటాయించిన ట్రిప్‌లు',
  TrKeys.tripHistory: 'ట్రిప్ చరిత్ర',
  TrKeys.advanceRequests: 'అడ్వాన్స్ అభ్యర్థనలు',
  TrKeys.salaryRequests: 'జీతం అభ్యర్థనలు',
  TrKeys.logout: 'లాగ్అవుట్',
  TrKeys.tripDetails: 'ట్రిప్ వివరాలు',
  TrKeys.startTrip: 'ట్రిప్ ప్రారంభించండి',
  TrKeys.confirmPickup: 'పికప్ నిర్ధారించండి',
  TrKeys.completeTrip: 'ట్రిప్ పూర్తి చేయండి',
  TrKeys.acceptTrip: 'అంగీకరించు',
  TrKeys.rejectTrip: 'తిరస్కరించు',
  TrKeys.from: 'నుండి',
  TrKeys.to: 'వరకు',
  TrKeys.vehicle: 'వాహనం',
  TrKeys.load: 'లోడ్',
  TrKeys.distance: 'దూరం',
  TrKeys.status: 'స్థితి',
  TrKeys.noTrips: 'ట్రిప్‌లు లేవు',
  TrKeys.tripAssigned: 'ట్రిప్ కేటాయించబడింది',
  TrKeys.acceptOrReject: 'మీకు కొత్త ట్రిప్ కేటాయించబడింది.',
  TrKeys.requestAdvance: 'అడ్వాన్స్ అభ్యర్థించండి',
  TrKeys.amount: 'మొత్తం (₹)',
  TrKeys.reason: 'కారణం',
  TrKeys.submit: 'సమర్పించు',
  TrKeys.advancePending: 'ఆమోదం వేచి ఉంది',
  TrKeys.advanceApproved: 'ఆమోదించబడింది',
  TrKeys.advanceRejected: 'తిరస్కరించబడింది',
  TrKeys.salary: 'జీతం',
  TrKeys.requestSalary: 'జీతం అభ్యర్థించండి',
  TrKeys.salaryPending: 'జీతం పెండింగ్',
  TrKeys.salaryApproved: 'జీతం ఆమోదించబడింది',
  TrKeys.salaryRejected: 'జీతం తిరస్కరించబడింది',
  TrKeys.earnedSalary: 'సంపాదించిన జీతం',
  TrKeys.approvedAmount: 'ఆమోదించిన మొత్తం',
  TrKeys.loading: 'లోడ్ అవుతోంది...',
  TrKeys.retry: 'మళ్ళీ ప్రయత్నించు',
  TrKeys.cancel: 'రద్దు చేయి',
  TrKeys.confirm: 'నిర్ధారించు',
  TrKeys.yes: 'అవును',
  TrKeys.no: 'కాదు',
  TrKeys.ok: 'సరే',
  TrKeys.error: 'లోపం',
  TrKeys.success: 'విజయవంతం',
  TrKeys.noData: 'డేటా అందుబాటులో లేదు',
  TrKeys.km: 'కి.మీ',
  TrKeys.rupee: '₹',
  TrKeys.notAssignedToOwner:
      'మీరు ఏ యజమానికి కేటాయించబడలేదు. అడ్మిన్‌ని సంప్రదించండి.',
  TrKeys.kycIncomplete:
      'KYC అసంపూర్ణం. దయచేసి మీ లైసెన్స్ అప్‌లోడ్ చేయండి.',

  // Tracking
  TrKeys.trackingActive: 'ట్రిప్ ట్రాకింగ్ యాక్టివ్‌గా ఉంది',
  TrKeys.trackingStarted: 'GPS ట్రాకింగ్ ప్రారంభమైంది',
  TrKeys.trackingStopped: 'GPS ట్రాకింగ్ ఆపివేయబడింది',
  TrKeys.gpsDisabled: 'GPS ఆఫ్ ఉంది. దయచేసి లొకేషన్ ఆన్ చేయండి.',
  TrKeys.enableGps: 'GPS ఆన్ చేయండి',
  TrKeys.locationPermissionRequired: 'ట్రిప్ ట్రాకింగ్ కోసం లొకేషన్ అనుమతి అవసరం.',
  TrKeys.backgroundLocationRequired: 'మీ ట్రిప్ ట్రాక్ చేయడానికి బ్యాక్‌గ్రౌండ్ లొకేషన్ యాక్సెస్ అవసరం.',
};
